version: "3.9"

services:
  postgres:
    build:
      context: ../shared/postgres
    image: starter-postgres:dev
    ports:
      - "5432:5432"
    networks:
      - network
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    volumes:
      - postgres_data:/var/lib/postgresql/data
    container_name: starter_postgres

  adminer:
    image: adminer
    networks:
      - network
    ports:
      - "8080:8080"

  flask:
    build:
      context: ../../
      dockerfile: envs/dev/back/Dockerfile
    image: starter-back:dev
    networks:
      - network
    volumes:
      - ../../:/code
    depends_on:
      - postgres
    env_file:
      - ./back/.env
    links:
      - postgres
    environment:
      - FLASK_APP=main.py
      - MIGRATION=1 # set 1 if you want to migrate
    ports:
      - "5678:5678"
      - "5001:5001"
    container_name: starter_back


volumes:
  postgres:
  postgres_data:


networks:
  network:
